- backend/build.gradle
- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- #47 
- spring 3.4.1에서 swagger사용시 @ConrollerAdvice를 사용할 수 없는 문제를 해결하기 위해 스프링 버전을 3.4.1 -> 3.3.8로 낮추었습니다.
- [참고 : [트러블슈팅] HY-THON - Swagger 500 에러: Failed to load API definition](https://dev-meung.tistory.com/entry/%ED%95%B4%EC%BB%A4%ED%86%A4-HY-THON-%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85-Swagger-500-%EC%97%90%EB%9F%AC-Failed-to-load-API-definition)
- 스웨거 버전도 2.3.0으로 향상하였습니다.
- 컨트롤러에 대해 swagger 설명을 추가하였습니다.
> docs: 스웨거와의 호환성을 위해 스프링 버전을 3.3.8로 낮춤

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
- backend/src/main/java/moadong/club/payload/response/ClubDetailedPageResponse.java
- backend/src/main/java/moadong/club/payload/response/ClubDetailedResponse.java
- backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
#53 
- 기존에 만들어진 상세페이지 조회 관련 api 명세서를 전체 목록 조회와 필드를 일치하기 수정
- 분과와 종류 추가
결과값
>
> [refactor] 상세페이지 조회 response 수정

- frontend/src/components/ClubLogo/ClubLogo.tsx
- frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
- frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.styles.ts
- frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
> #48
로고 이미지, 이름, 분류, 분과, 태그들을 Props로 받음
- 살면서 짜본 CSS중 제일 어려웠으나 다행히 성공
- 결과물은 별거 아닌 것 같지만.....진짜 갈아넣었네욤😭
[데스크탑]
[모바일]
<br />
onClick()을 Props로 받음
[데스크탑]
[모바일]
<br />
https://github.com/user-attachments/assets/b0537b87-4c38-47b1-861c-beed5c73c3bc
<br />
혹시 놓친 부분이나 개선할 점이 있다면 피드백 부탁드립니다.
이거 지원하기 버튼 모바일 버전이랑 구분해서 만들긴했는데 이거 어캐 배치할까용?
따로 만들어야할 것 같기도 하고요
> [feature] 상세 페이지: 프로필 및 지원하기 버튼 컴포넌트 추가

- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
- backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
- #84 
erd cloud의 erd를 아래와 같이 수정하였습니다.
api 변경사항을 명세서에 반영하였습니다.
https://www.notion.so/c2068f8c4e6e459aa017ed62e2a75abe
- **statusCode** (String) → ✅ 그대로 유지 (`statuscode` → `statusCode`로 변경 가능)
- **message** (String) → ✅ 그대로 유지
- **data** (Object) → ✅ 그대로 유지
- **club** (Object) → ✅ `clubId`, `clubName`, `clubImageUrl` 등을 `club` 객체 안으로 이동
- **id** (String) → 🔄 기존 `clubId`에 해당
- **name** (String) → 🔄 기존 `clubName`에 해당
- **logo** (String) → 🔄 기존 `clubImageUrl`에 해당 (`null` 가능)
- **tags** (List<String>) → ✅ 기존 `clubTags`와 동일
- **state** (String) → 🔄 기존 `clubState`
- 기존에는 `"모집 중"`, `"모집 마감"`, `"모집 예정"`이었는데,새로운 응답에서는 `"활성화"` 등의 표현 사용
- **feeds** (List<String>) → ✅ 기존 `clubFeeds`와 동일
- **description** (String) → 🔄 기존 `소개 글`
- **presidentName** (String) → 🔄 기존 `president`
- **presidentPhoneNumber** …
> [feature] 모집정보 추가

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/controller/ClubMetricController.java
- backend/src/main/java/moadong/club/entity/ClubMetric.java
- backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
- backend/src/main/java/moadong/club/service/ClubMetricService.java
- #83 
특정 동아리를 지목하여 일간, 주간, 월간 통계를 조회하는 기능을 구현하였습니다.
단수형이였던 collection이름들을 모두 복수형으로 변경하고, 데이터를 옮겨두었습니다.
새로운 GCP 인스턴스구축을 위한 계정(Pororo)에 erd cloud를 전부 복제 및 업데이트 해두었습니다.
<br>
- MongoDB는 오로지 UTC만을 적용합니다. 따라서, 저장시에 한국시간으로 변경해도 의미가 없으며, 조회시 한국시간으로 변화하는 과정이 꼭 필요합니다.
> [feature] 통계관련 엔티티 및 기능 구현

- frontend/config/webpack.dev.ts
- frontend/package-lock.json
- frontend/package.json
> ex) #100 
자동으로 localhost의 port 탐색이 가능하도록 개선하였습니다.
```typescript
import detectPort from 'detect-port';
const DEFAULT_PORT = 3000;
async function getAvailablePort(defaultPort: number): Promise<number> {
return await detectPort(defaultPort);
}
```
- [detect-port](https://www.npmjs.com/package/detect-port) 를 사용
- <code>detectPort(defaultPort)</code> : 비동기적으로 사용 가능한 포트를 반환하는 함수
>
> [chore] 자동 포트 탐색 기능

- frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
- frontend/src/pages/MainPage/components/Banner/Banner.tsx
> ex) #103 
> 3초마다 배너가 자동으로 넘어가도록 합니다
- useEffect 내부에서 3초마다 실행
- 배너의 수(banner.length)가 바뀔 때마다 재생성
- useEffect로 인해 생기는 불필요한 리렌더링을 방지
- **배너의 수**가 바뀌지 않는 한 같은 함수 인스턴스를 유지하여 불필요하게 useEffect가 실행되는 것을 방지하기 위함
- <code>extendedBanners</code>: 기존 banner에 첫번째 슬라이드를 추가
- 마지막 슬라이드에서 첫번째 슬라이드로 이동된 후, 애니메이션을 없앤 상태에서 **다시 첫번째 슬라이드로 전환**시킴으로써 사용자는 무한으로 배너가 돌아가는 것처럼 인식
- <code>transitionEndHandler</code>함수가 마지막 슬라이드 혹은 첫번째 슬라이드인지 인식하여 애니메이션 효과를 일시적으로 없앰
1. <code> moveToPrevSlide</code>에도 useCallback 적용
2. 배너 타입  BannnerProps를 <code>Banner.tsx</code>로 이동
>
> [feature] 배너 자동 슬라이드

- frontend/src/App.tsx
- frontend/src/apis/getClubDetail.ts
- frontend/src/hooks/queries/club/useGetClubDetail.ts
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
- frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
- frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
- frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
- frontend/src/types/club.ts
> ex) #119 
- InfoBox 8878a30980b4aa26c11abd46ea067a15449f682d
- ClubProfile a46cabf41203c313a5c5be492149d6c32b4e5992
- tanstack-query 적용 2308178d950ef1976ac417621c65e6df877ad656
- IntroduceBox api 연결 e135f0b184e2940ad5af3080975e21e9d0cadb6e
- 상세페이지 useEffect 제거 및 tanstack-query적용 2308178d950ef1976ac417621c65e6df877ad656
- 메인페이지 카드 애니메이션 추가 81c9607e97a0e7a3b50107338aeaa15e7e890f47
>
> [feature] 상세페이지 api 연동

- frontend/config/webpack.common.ts
- frontend/package-lock.json
- frontend/package.json
> #145
✅ 주요 변경 사항
copy-webpack-plugin 추가 및 webpack.config.ts에 적용
public/ 폴더 내 favicon.ico, sitemap.xml, robots.txt 등을 dist/로 자동 복사
>
> [feature] 번들링 시 public/ 폴더 내용 복사

- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- backend/src/main/java/moadong/gcs/domain/FileType.java
- backend/src/main/java/moadong/gcs/dto/FeedDeleteRequest.java
- backend/src/main/java/moadong/gcs/dto/FeedUpdateRequest.java
- backend/src/main/java/moadong/gcs/dto/ImageDeleteRequest.java
- backend/src/main/java/moadong/gcs/service/ClubImageService.java
> ex) #199 
> 로고와 피드 이미지 업로드 및 삭제 기능 구현 및 리팩터링
---
- 로고의 경우 1개의 로고 이미지만 유지되어 새로운 로고가 추가될 경우 이전의 로고는 삭제되도록 구현하였고 별개로 로고의 Delete 요청도 가능하게 구현하였습니다.
---
- 이미지 업로드 관련하여 logo와 feed를 분류할 수 있는 FileType Enum을 추가하였습니다.
---
- 피드 업로드 기능을 분리하여 구현하였는데, 이는 추후 Signed  URL을 통해 프론트 측에서 파일을 직접 클라우드에 올리는 방식으로 수정될 것을 대비하여 미리 분리해 두었습니다.
- 현재는 MultipartFile을 받아 백엔드 서버에서 업로드해 주는 방식으로 구현하여 정상적으로 동작되도록 하였습니다.
- 또한 현재는 Post 메서드로 구현되어 있지만 Signed URL이 구현될 경우 Get 메서드로 수정될 예정입니다.
- 추후 Signed url 작업이 필요한 곳은 TODO로 표시해 두었습니다.
---
- 피드 이미지는 Post 메서드로 통일하여 저장하도록 하였습니다.
- post 요청시 저장되어 있는 정보와 새로 들어온 정보를 비교하여 없어진 데이터를 자동으로 삭제 요청하도록 수정하였습니다.
- 이를 통해 사진을 삭제하고 싶다면 별다른 Delete 요청이 아닌 Post 요청으로 삭제하고 싶은 url만 제외하고 보내면 자동으로 삭제되도록 구현되었습니다.
> 로고와 피드 이미지 업로드 및 삭제 기능 구현 및 리팩터링

- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
> #211 
update 메소드 사용 시 update와 관련없는 필드가 사라지는 문제
```
public void update(ClubInfoRequest clubInfoRequest){
this.recruitmentEnd = clubInfoRequest.recruitmentEnd();
this.recruitmentStart = clubInfoRequest.recruitmentStart();
this.presidentName = clubInfoRequest.clubPresidentName();
this.presidentTelephoneNumber = clubInfoRequest.telephoneNumber();
this.recruitmentTarget = clubInfoRequest.recruitmentTarget();
this.introduction = clubInfoRequest.introduction();
this.tags = clubInfoRequest.tags();
}
```
-> 기존 빌더 패턴에서 update 메소드를 추가해 변경사항만 수정하도록 반영
> [fix] 동아리 수정 시 발생하는 필드 누락 문제 해결

- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/user/controller/UserController.java
- backend/src/main/java/moadong/user/payload/response/FindUserClubResponse.java
- backend/src/main/java/moadong/user/payload/response/LoginResponse.java
- backend/src/main/java/moadong/user/service/UserCommandService.java
> #227 
Club Entity에 userId 필드 추가
>
> [feature]JWT 토큰 전달 시 관리자가 생성한 동아리 아이디 반환 API 추가

- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
- backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
- backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
#️⃣연관된 이슈
> ex) #239 
상세 정보 조회시에 null 값이 들어오면 빈칸처리
검색 시에 로고와 태그가 null이면 빈칸처리
> [refactor]상세 조회 시 DB 필드가 없는 겂들이 null로 반환되던 걸 blank로 변경

- frontend/src/hooks/queries/club/useUpdateClubDescription.ts
- frontend/src/hooks/queries/club/useUpdateClubDetail.ts
- frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.tsx
- frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
- frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
- frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/types/club.ts
> ex) #236 
> 변경 전
```typescript
export const useUpdateClubDescription = () => {
const queryClient = useQueryClient();
return useMutation({
mutationFn: (updatedData: ClubDescription) =>
updateClubDescription(updatedData),
onSuccess: async () => {
await queryClient.invalidateQueries({
queryKey: ['clubDetail'],
});
},
onError: (error) => {
console.error('Error updating club detail:', error);
},
```
> 변경 후
```typescript
export const useUpdateClubDescription = () => {
return useMutation({
mutationFn: (updatedData: ClubDescription) =>
updateClubDescription(updatedData),
onError: (error) => {
console.error('Error updating club detail:', error);
},
});
};
```
> 변경 이유
1. **GET 요청으로 항상 최신 상태를 보장하고 있음**
- `invalidateQueries(['clubDetail'])`는 **클럽 상세 데이터를 다시 불러오는 역할**인데,
- 상세페이지에서 get 으로 항상 최신의 상태를 …
> [refactor] tanstackQuery 최적화 및 활동사진 컴포넌트 리팩토링

- frontend/src/components/common/SearchBox/SearchBox.tsx
> ex) #249 
- 메인페이지가 아닌 다른 모든 페이지에서 검색창 클릭시 메인페이지로 리다이렉트 370fbfda229aa0c766f8acd281c3d62e17d6572c
- [노션-트러블슈팅](https://www.notion.so/1c7aad23209680c8be6ae69d4821875f?pvs=4) 
>
> [fix] 상세페이지 검색창 클릭 시 메인페이지로 이동

- frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
- frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.styles.ts
- frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.tsx
> [style] 관리자페이지 회원정보관리 UI 수정

- frontend/src/App.tsx
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
> [refactor] 상세페이지 url 클럽이름으로 변경

- backend/src/main/java/moadong/user/util/CookieMaker.java
https://github.com/Moadong/moadong/issues/259
로그아웃 엔드포인트 추가(클라이언트측의 리프레시 토큰 강제 삭제)
리프레시 토큰의 사용처 인증 추가(DB와 비교하여 리프레시 토큰 발급자가 리프레시 토큰을 전송했는지 검증)
아이디 비밀번호 수정은 연기
이미 머지 했던 브랜치인데 긴급 버그 수정으로 다시 살렸습니다.
> [feature] 로그아웃 및 리프레쉬 토큰 관련 기능

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/controller/ClubMetricController.java
- backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/club/service/ClubMetricService.java
- #248 
- 기존에 request가 nginx를 거쳐 들어오면 172.18.0.1로 통일되는 문제를 해결하고, 실제 요청을 보낸 ip주소를 메트릭으로 저장합니다.
- 동아리를 인기순으로 조회합니다. 파라미터에 따라 개수를 지정할 수 있습니다.
> [feature] 일일 인기동아리 조회

- frontend/src/pages/MainPage/MainPage.styles.ts
- frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
> ex) #286 
- 카테고리 버튼에 clubCard가 닿는 경우 border-shadow가 없어지는 효과 제거 d1b025085baec9654fed63522b1a72531bf04dfd
- clubCard와 라디오버튼 사이 
- 카테고리버튼과 배너 사이
>
> [fix] 메인페이지 스타일 수정

- frontend/src/apis/auth/login.ts
- frontend/src/apis/auth/logout.ts
- frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
> #284 
로그아웃 요청 시, 서버에서 refresh_token을 삭제하고, HttpOnly 쿠키를 만료 처리하도록 구현
<br />
로그인 시, 서버에서 refresh_token을 HttpOnly 쿠키로 설정하고, credentials: 'include' 설정을 통해 자동으로 쿠키를 관리
> [feature] 로그아웃 API 연결 및 로그인 시 HttpOnly 쿠키 처리

- frontend/src/apis/createFeedImage.ts
- frontend/src/apis/updateClubLogo.ts
- frontend/src/constants/uploadLimit.ts
- frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
- frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
> ex) #298 
```typescript
if (file.size > MAX_FILE_SIZE) {
throw new Error('파일 크기가 10MB를 초과합니다.');
}
```
- 로고 및 활동사진 업로드 api에 파일 크기 조건을 추가했습니다.
```typescript
const files = event.target.files;
if (files) {
const file = files[0];
if (file.size > MAX_FILE_SIZE) {
alert('파일 크기가 10MB를 초과합니다.');
return;
}
```
- 파일크기 조건을 한 번 더 검사하여 무결성을 높였습니다.
- 동시에 alert창을 추가했습니다.
>
> [feature] 활동사진, 로고파일 최대용량 10MB로 설정

- backend/src/main/java/moadong/club/controller/ClubMetricController.java
- backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
- backend/src/main/java/moadong/club/service/ClubMetricService.java
- 상세페이지를 조회한 일일 활성 사용자수를 조회합니다. 이때, 같은 ip는 1로 카운트 됩니다.
- #313 
- api 구현
- 로컬테스트
- [api 명세서 작성](https://www.notion.so/1d0aad23209680409d2fd610e811253a)
- 기능 명세서 작성
> feat : 사이트 일일 활성사용자수 조회

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
- frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
- frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
- frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
- frontend/src/utils/getDeadLineText.test.ts
- frontend/src/utils/getDeadLineText.ts
> ex) #311 
1. 모집인 경우 -> 모집링크로 변경
- 구글폼 있을 시 리다이렉트
- 없다면 alert ```{번호}로 연락주세요!```
2. 모집이 아닌 경우 -> 모집 마감으로 처리
- alert ```모집이 마감되었습니다. 다음에 지원해 주세요!```
1. clubDetailPage -> clubDetailHeader -> clubApplyButton
2. clubDetailPage -> clubDetailFooter -> deadlineText, clubApplyButton
-> prop을 2단계로 전달하는 것까지 큰 문제는 없다고 생각했습니다. 
- [9ad9a18](https://github.com/Moadong/moadong/pull/312/commits/9ad9a1891c3b5b5cf9b0e8c4d48c9aadcc68ec82)
- jsdom 패키지 설치
>
현재 모집 중인 동아리는 모두 상시모집인데 구글폼을 사용하지 않아서 구글폼 리다이렉트 로직은 추가하지 않았습니다.
> [feature] 상시모집 동아리 alert창에 전화번호 띄우기

- backend/src/main/java/moadong/club/service/ClubSearchService.java
#️⃣연관된 이슈
> #327 
같은 카테고리안에 속한 동아리들 검색 결과에서 동아리 이름 오름차순에 따라 정렬되도록 변경한다.
단, 영어 이후 한글로 정렬합니다.
> [feature]검색 결과가 동아리 이름 오름차순으로 정렬되도록 변경

- frontend/jest.config.js
- frontend/package-lock.json
- frontend/package.json
> #421 (테스트 환경에서 이미지 파일 import 시 SyntaxError 발생)
- `jest-transform-stub` 라이브러리 설치
- `jest.config.js`에 `.svg`, `.png` 등 이미지 파일에 대한 transform 설정 추가
- 테스트 시 이미지 import 관련 SyntaxError(`Unexpected token '<'`) 문제 해결
- `SNS_CONFIG` 객체에 플랫폼별 아이콘(SVG/PNG)을 import하여 사용하는 로직이 추가되면서 테스트 실행 시 다음과 같은 에러 발생
```ts
SyntaxError: Unexpected token '<'
```
- 이는 Jest가 `.svg` 파일을 JS처럼 파싱하려다 실패한 문제로, 정적 파일에 대한 처리 설정이 누락된 상태였음
그래서 해결 방법은 이런 정적 파일들을 모두 가짜(mock) 파일로 치환하거나 특정 도구 (jest-transform-stub)로 처리 규칙을 명시해줘야함
- `jest-transform-stub`을 도입하여 `.svg`, `.png` 등 정적 에셋을 mock 처리 - 쉽게 말하면 이미지를 문자열로 대체!!
- Jest 설정 파일(`jest.config.js`)에 이미지 파일을 위한 `transform` 항목 추가
- [`jest-transform-stub` npm 페이지](https://www.npmjs.com/package/jest-transform-stub)
- [Jest 공식 문서 - Code …
> [fix] Jest 테스트 시 SVG import 오류 해결
