- .gitignore
- frontend/.gitignore
- frontend/.prettierrc
- frontend/config/webpack.common.ts
- frontend/config/webpack.dev.ts
- frontend/config/webpack.prod.ts
- frontend/eslint.config.mjs
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/index.tsx
- frontend/tsconfig.json
> #2
Devlop/fe 브랜치로 frontend 환경 세팅 merge
> [chore] frontend setup

- frontend/src/App.tsx
- frontend/src/styles/Global.styels.ts
> #6
> 1. Global.styles.ts 생성
> 2. App.tsx에 글로벌 스타일 적용
> [chore] frontend Global style 설정

- backend/build.gradle
- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubFeedImages.java
- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/entity/ClubTags.java
- backend/src/main/java/moadong/club/enums/ClubState.java
- backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
- backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/club/repository/ClubTagRepository.java
- backend/src/main/java/moadong/global/RegexConstants.java
> issue #8
- clubs
- clubInformations
- clubTags
- clubFeedImages 
**ClubState**
클럽 상태를 나타내는 enum
```
public enum ClubState {
UNAVAILABLE,
AVAILABLE,
}
```
**RegexConstants**
validation에 필요한 정규식 상수
```
public final class RegexConstants {
public static final String PHONE_NUMBER = "\\d{2,3}-\\d{3,4}-\\d{4}";
public static final String EMAIL = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
private RegexConstants() {
throw new UnsupportedOperationException("이 클래스는 인스턴스로 만들면 안됩니다!");
}
}
```
1. 모든 클래스를 외래키 참조형식으로 구성하지 않았습니다.
2. ClubInformation을 구성할 때,
```
@Pattern(regexp = RegexConstants.PHONE_NUMBER, message = "전화번호 형식이 올바르지 않습니다.")
@Column(length = 13)
private String telephoneNumber;
```
위와 같이 Pattern 어노테이션을 사용하여 Validation을 하는 식으로 진행하였는데 어떻게 생각하시는지 궁금합니다.
> feat: 엔티티 생성

- backend/build.gradle
- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/dto/ClubCreateRequest.java
- backend/src/main/java/moadong/club/dto/ClubUpdateRequest.java
- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubFeedImages.java
- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/entity/ClubTags.java
- backend/src/main/java/moadong/club/enums/ClubState.java
- backend/src/main/java/moadong/club/payload/dto/ClubFeedImageProjection.java
- backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
- backend/src/main/java/moadong/club/payload/dto/ClubTagProjection.java
- backend/src/main/java/moadong/club/payload/dto/ClubThumbnailProjection.java
- backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
- backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
- backend/src/main/java/moadong/club/payload/response/ClubDetailedPageResponse.java
- backend/src/main/java/moadong/club/payload/response/ClubSearchResponse.java
- backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
- backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/club/repository/ClubTagRepository.java
- backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
- backend/src/main/java/moadong/club/service/ClubSearchService.java
- backend/src/main/java/moadong/club/service/ClubService.java
- backend/src/main/java/moadong/global/config/SecurityConfig.java
> #13 
동아리 상세페이지
- 동아리 상세페이지를 개설한다.
- 수정기능 구현
- 첫 수정시, 다른 사용자들에게 노출되도록 상태 변경
- 상세페이지를 조회
동아리 전체 목록
- 모집 중, 모집 아님 구분하여 리스트로 출력
>
> feat: 동아리 상세 페이지 및 전체 목록 출력(Feat/#13 to develop/be)

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/club/repository/ClubTagRepository.java
- backend/src/main/java/moadong/club/service/ClubCommandService.java
- backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
- backend/src/main/java/moadong/club/service/ClubSearchService.java
- backend/src/main/java/moadong/global/exception/ErrorCode.java
- backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
- backend/src/main/java/moadong/global/exception/RestApiException.java
- backend/src/main/java/moadong/global/payload/Response.java
- #19 
- 리팩토링
- [컨벤션 문서화](https://github.com/pknu-wap/Moadong/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EA%B0%9C%EB%B0%9C-%EC%BB%A8%EB%B2%A4%EC%85%98)
기존 개발된 기능에 대하여 리팩토링 및 컨벤션을 문서화하였습니다. 아직까지는 혼동될만한 부분이 많지 않은것 같아 간소하게 작성하였습니다. 이후에 원하는 컨벤션을 추가하고 싶거나, 논의 사항이 생기면 추가 및 숙지하는 것이 좋을 것이라 판단됩니다.
> [Refactor] 커스텀 응답/예외 처리 및 리팩토링

- .github/workflows/gradle-develop-publish.yml
- .github/workflows/gradle-release-publish.yml
- backend/Dockerfile
> ex) #9 
> 누락되었던 Dockerfile 추가했습니다
> 또한 github action 파일의 path 경로에 github action 파일이 수정되는 경우도 추가했습니다
>
> [chore] Dockerfile 추가

- frontend/.gitignore
- frontend/.storybook/main.ts
- frontend/.storybook/preview.ts
- frontend/chromatic.config.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Button/MyButton.stories.tsx
- frontend/src/components/Button/MyButton.tsx
> ex) #16 
[React + Storybook 적용](https://velog.io/@seongwon__105/React-Storybook-적용)에 스토리북 적용과 chromatic을 이용한 배포 과정까지 기록하였습니다. 
스토리북을 적용하면서 추가로 스토리 파일에 코드를 작성하여야 한다는 점에 대해 어떻게 생각하시는지 궁금합니다.
> [chore] Storybook을 적용한다

- backend/build.gradle
- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/payload/dto/ClubInformationSearchProjection.java
- backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
- backend/src/main/java/moadong/club/payload/dto/ClubThumbnailProjection.java
- backend/src/main/java/moadong/club/payload/response/ClubDetailedPageResponse.java
- backend/src/main/java/moadong/club/payload/response/ClubSearchResponse.java
- backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
- backend/src/main/java/moadong/club/repository/ClubRepository.java
- backend/src/main/java/moadong/club/repository/ClubTagRepository.java
- backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
- backend/src/main/java/moadong/club/service/ClubSearchFilterService.java
- backend/src/main/java/moadong/club/service/ClubSearchService.java
> #22 
- 동아리 전체 목록 조회에 동아리 분과랑 소속을 추가하도록 한다.
- 동아리 전체 목록 조회에 다음 결과를 리턴하도록 한다.
- 엔티티 ClubInformation 필드명 변경
- telephoneNumber -> presidentTelephoneNumber
- clubPresidentName -> presidentName
- thumbnail -> logo
```
@Service
@AllArgsConstructor
public class ClubSearchFilterService {
private final ClubRepository clubRepository;
private final ClubInformationRepository clubInformationRepository;
private final ClubTagRepository clubTagRepository;
public ClubSearchResponse getClubsByFilter(
String availability,
String classification,
String division
) {
List<Club> clubs = searchClubsByFilter(availability, classification, division)
.orElseThrow(() -> new RestApiException(ErrorCode.CLUB_NOT_FOUND));
List<ClubSearchResult> clubSearchResults = new ArrayList<>();
for (Club club : clubs) { …
```
> [feature & refactor]전체 목록 검색 시 동아리 분과, 소속 추가와 결과값 수정 및 엔티티 변수 리팩토링

- frontend/src/components/ClubLogo/ClubLogo.tsx
- frontend/src/components/ClubStateBox/ClubStateBox.tsx
- frontend/src/components/ClubTag/ClubTag.tsx
- frontend/src/pages/MainPage/components/ClubCard.styles.ts
- frontend/src/pages/MainPage/components/ClubCard.tsx
- frontend/src/styles/Global.styels.ts
> #14 
<br />
<br />
- 동아리 상세 페이지에도 쓰일 것을 고려해서 두가지 상태(small/large)로 만들었습니다.
<br />
-  API에서 받아와서 바로 띄울 수 있도록 객체 키 값 고려하여 만들었습니다!
```js
const clubDataList = [
{
id: 'abc',
name: 'WAP',
logo: 'https://example.com/react-club.jpg',
tags: ['프로젝트', '소프트웨어'],
state: '모집중',
division: '중동',
classification: '학술',
description: '개발자들이 모여있습니다.',
},]
{clubDataList.map((club) => (
<ClubCard key={club.id} club={club} />
))}
```
- Pretendard 글씨체 CDN 방식으로 적용
<br />
새로운 타입 정의 방식을 사용했습니다. 첫 시도라 실수가 있을 수 있으니 확인 부탁드립니다!
이 방식들이 적절한지, 혹은 더 나은 대안이 있다면 검토 부탁드립니다.
<br />
1. 상태별 타입 설정
상태(state)에 따라 동적인 디자인을 적용하기 위해 Record<string, string>을 사용했습니다.
```js
const stateStyles: Record<string, string> = {
모집중: '파란색 스타일',
모집마감: '회색 스타일',
};
```
<br />
2. 유니온 타입 활용
컴포넌트의 logoSize에 특정 값(small/large)만 허용하도록 제한하기 위해 유니온 타입을 …
> [feature] 동아리 카드 컴포넌트 제작

- frontend/src/components/@common/Footer/Footer.styles.ts
- frontend/src/components/@common/Footer/Footer.tsx
> #40 
> Footer 빠르게 제작 완료
피그마 참고해서 500px 이하 반응형 적용해뒀슴니다
https://github.com/user-attachments/assets/56f3e473-631c-408f-97b4-849cd7328e38
1. 모아동 이메일을 만들 필요가 있음 
moadong@gmail.com은 있네여 ㅠ
> [feature] Footer 컴포넌트 제작

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/payload/dto/ClubInformationSearchProjection.java
- backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
- backend/src/main/java/moadong/club/repository/ClubKeywordSearchRepository.java
- backend/src/main/java/moadong/club/repository/ClubKeywordSearchRepositoryImpl.java
- backend/src/main/java/moadong/club/service/ClubSearchFilterService.java
- backend/src/main/java/moadong/club/service/ClubSearchService.java
#️⃣연관된 이슈
#37 
동아리 이름, 태그, 설명을 통해 키워드 검색을 한다
- 동아리 이름 검색
- 동아리 태그 검색
- 동아리 설명 검색
- 위 3가지 기능 합치기
```
package moadong.club.repository;
import lombok.AllArgsConstructor;
import moadong.club.payload.dto.ClubSearchResult;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.aggregation.Aggregation;
import org.springframework.data.mongodb.core.aggregation.AggregationResults;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.stereotype.Repository;
import java.util.List;
@Repository
@AllArgsConstructor
public class ClubKeywordSearchRepositoryImpl implements ClubKeywordSearchRepository {
private final MongoTemplate mongoTemplate;
@Override
public List<ClubSearchResult> searchResult(String keyword) { …
```
> [feature]검색 기능 추가

- .github/workflows/gradle-develop-publish.yml
- .github/workflows/gradle-release-publish.yml
- .github/workflows/pr-test.yml
> #50 
>  PR시 자동으로 지정된 모든 테스트를 통과하는지 검사하는 기능 구현
> PR의 모든 check status가 체크되지 않으면 merge되지 않도록 브랜치 rule 생성
>
> [chore] PR시 자동으로 지정된 모든 테스트를 통과하는지 검사

- frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
- frontend/src/pages/MainPage/components/Banner/Banner.tsx
> ex) #45 
1. 이미지 반응형 완료했습니다.
2. 무한 캐러셀은 아직 미완입니다.. 반드시 12일안으로 할 예정
>
> [feature] 캐러셀 반응형 적용

- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- backend/src/main/java/moadong/global/config/SwaggerConfig.java
- backend/src/main/java/moadong/global/config/WebConfig.java
- backend/src/main/java/moadong/global/util/OctetStreamReadMsgConverter.java
- #60 
- server.domain을 통해 https의 서버를 특정하여 swagger 사용 가능케 함
- application.properties에 `server.domain`관련 설정값이 추가됨 (노션 업데이트 완료)
- 스웨거에서 파일 업로드가 가능케 함
- application/octet-stream을 읽기로 다루는 컨버터를 정의
- 컨트롤러에 파일 업로드 가능하도록 설정 추가
> [Fix] Swagger 설정 변경

- backend/src/main/java/moadong/club/controller/ClubController.java
> feat : 클럽 생성후 클럽 id 반환

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/global/payload/Response.java
- #68 
- 리스폰스 메시지는 따로 작성가능케 한다.
> feat : 리스폰스 메시지 직접 지정 가능

- backend/src/main/java/moadong/club/entity/ClubFeedImage.java
- backend/src/main/java/moadong/club/entity/ClubTag.java
- backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
- backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
- backend/src/main/java/moadong/club/repository/ClubTagRepository.java
- backend/src/main/java/moadong/club/service/ClubCommandService.java
- backend/src/main/java/moadong/gcs/service/ClubImageService.java
- #72 
- 클럽 수정시 기존 태그를 전부 지우고 새로운 태그를 작성합니다.
> [fix] 클럽 태그를 수정할 수 있다

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
- backend/src/main/java/moadong/club/service/ClubCommandService.java
- backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
- backend/src/main/java/moadong/global/config/SchedulerConfig.java
- #74 
- 동아리 모집일정은 시간 단위로 이루어져야할 것 같아서 `LocalDate` -> `LocalDateTime`으로 변경하였습니다.
- 동아리 수정시 스케쥴러에 모집일정에 관한 데이터를 동적으로 달아두고, 해당 시간이 되면 모집 상태를 변경하도록 수정하였습니다.
> [feature] 모집일정에 따른 모집상태 자동 변경

- backend/src/main/java/moadong/global/config/SecurityConfig.java
#78 
프론트 배포 진행 후 웹브라우저에서 서버 API 요청 시에 CORS 에러 발생하였습니다.
```
@Bean
public UrlBasedCorsConfigurationSource corsConfigurationSource() {
CorsConfiguration configuration = new CorsConfiguration();
configuration.setAllowedOriginPatterns(Arrays.asList(serverDomain, "http://localhost:*"));
configuration.setAllowedMethods(Arrays.asList("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"));
configuration.setAllowedHeaders(Arrays.asList("Authorization", "Content-Type", "X-Requested-With"));
configuration.setExposedHeaders(Arrays.asList("Authorization", "Content-Type"));
configuration.setAllowCredentials(true);
UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
source.registerCorsConfiguration("/**", configuration);
return source; …
```
> chore: SecurityConfig에 cors 관련 설정 추가

- backend/src/main/java/moadong/global/config/SecurityConfig.java
#78 
#79 
application 프로퍼티에 프론트 도메인란을 추가하였습니다.
자세한 내용은 노션을 확인해주세요.
> fix: cors 주소를 올바르게 변경

- frontend/src/apis/getClubList.ts
> #114
카드가 안뜨는 원인 파악했는데 머지를 해야 테스트가 가능하네요..
> [refactor] 메인페이지 검색 API 반환값 수정

- frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
- frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
> ex) #115 
- 줄바꿈 2번이상은 무조건 2번까지만 허용해놓았습니다
>
번호나 li태그는 에디터가 필요할까요?
> [feature] 관리자 페이지 소개글 에디터 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/Header/Header.styles.ts
- frontend/src/components/common/Header/Header.tsx
- frontend/src/components/common/SearchBox/SearchBox.tsx
- frontend/src/hooks/useMixpanelTrack.ts
- frontend/src/hooks/useTrackPageView.ts
- frontend/src/index.tsx
- frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
- frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
- frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
- frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
> ex) #123 
- ab5e229f3999fc5aa734300a27c2dd1bab2921c1
- [pageView에 대한 정리](https://honorable-cough-8f9.notion.site/1aeaad232096804dbcd3e21f557a5a5e?pvs=4)
- Header의 홈, 소개 버튼
- 검색아이콘 
- 카테고리 버튼 (각각 다른 이벤트)
- 모집여부 라디오버튼
- 이벤트카드
- 모바일 헤더 홈,검색,메뉴 버튼 
- 상세페이지 지원하기 버튼
>
더 추가할만한 이벤트가 있을까요?
> [feature] 믹스패널 적용

- frontend/src/App.tsx
- frontend/src/components/common/SearchBox/SearchBox.tsx
- frontend/src/context/SearchContext.tsx
- frontend/src/pages/MainPage/MainPage.tsx
> ex) #128 
> context api로 search keyword를 전역적으로 관리하였는데 이 부분을 중점으로 봐주시면 좋겠습니다.
> [feature] 검색 api 연동 

- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
> [fix] 카테고리 선택에 따른 검색 키워드 매핑 추가 수정

- frontend/src/components/common/Footer/Footer.styles.ts
- frontend/src/components/common/Footer/Footer.tsx
> #138
1. Footer 하단 고정 16929e213e2381a69e9963a132a5bf94bc7eb38a
2. Footer에 모아동 이메일 추가 cea409ec55fde2ce162e6e530a4149fd1531f9e0
>
> [fix] Footer UI 수정

- frontend/src/components/common/Header/Header.styles.ts
> [fix] 헤더 padding 설정 

- frontend/public/robots.txt
- frontend/public/sitemap.xml
> #141
1. robots.txt 추가 80c8bd82a3cfa5da986fe5d85a8b95a32c00705c
2. sitemap.xml 추가  8a081e1799dc84cc65c82b7bdcec945cd8d470d9
> [feature] sitemap.xml, robots.txt 추가

- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
- backend/src/main/java/moadong/user/entity/User.java
- backend/src/main/java/moadong/user/entity/UserInformation.java
- #151 
- 동아리 수정시 로고는 건드리지 않습니다.(api 따로 있음)
- 테이블 이름들을 복수형으로 바꿨습니다.
> [fix] logo

- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
> ex) #154 
- division과 classification 순서 변경 
>
> [refactor] ClubCard 태그순서 변경

- backend/src/main/java/moadong/club/entity/ClubInformation.java
- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
- backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
- #157 
- 하드 코딩된 컬렉션 이름을 수정하였습니다.
- 또한, 모집기간이 지정되어 있지 않을 경우 발생하는 예외를 처리합니다.
> [fix] 컬렉션 이름 변경에 따른 사이드 이펙트 대응

- .github/ISSUE_TEMPLATE/issue-form.yml
> ex) #162 
> jira 이용을 위한 이슈템플릿 추가
>
> [chore] jira 이슈 템플릿 제작

- .github/workflows/server_cd_release.yml
> ex) #82 
> 오타로 인한 배포서버 ci/cd 에러 수정
> fix : 오타로 인한 배포서버 ci/cd 에러 수정

- frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
- frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
> ex) #156 
- 상세페이지 박스 간 gap 줄임
- Title 폰트 400 -> 500으로 변경
>
> [style] 상세페이지 InfoBox 간격수정 및 제목굵기 변경

- frontend/src/apis/getClubList.ts
- frontend/src/hooks/queries/club/useGetCardList.ts
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
- frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
- frontend/src/types/club.ts
> [refactor] 동아리 분과 정보 네이밍 변경

- README.md
> [docs]리드미 수정

- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
- backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
- backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
- 메인화면에서 조건없음으로 검색이 안되는 문제를 해결합니다.
- 모집폼 링크에 대한 정보를 반환합니다.
> [release] BE 1-4차 배포

- frontend/src/pages/MainPage/MainPage.tsx
> #196 
- category와 division 값이 서로 바뀌어 할당되는 버그 수정
- 올바른 값이 적용되도록 코드 수정
> [fix] 카테고리 버튼에 맞는 카드 렌더링

- frontend/src/index.tsx
> ex) #214 
```typescript
if (window.location.hostname === 'localhost') {
mixpanel.disable();
}
```
이제 localhost 추적 비활성화됩니다.
>
> [chore] mixpanel 로컬호스트 추적 방지

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/controller/ClubMetricController.java
- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- backend/src/main/java/moadong/global/config/SecurityConfig.java
- backend/src/main/java/moadong/user/controller/UserController.java
#215 
#35 
위 두 이슈 참고 부탁드립니다.
비활성화해둔 어드민 인증 기능을 활성화 합니다.
> chore: 인증 활성화

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/club/entity/Club.java
- backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
- backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
- backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
- backend/src/main/java/moadong/club/service/ClubCommandService.java
#210 
develop 머지가 안돼고 메인에 돼서 다시 올립니다
> [refactor] api 필드 분리 및 이름 통일

- backend/src/main/java/moadong/club/controller/ClubController.java
- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- backend/src/main/java/moadong/user/controller/UserController.java
- backend/src/main/java/moadong/user/view/UserSwaggerView.java
- #245 
- 스웨거 설명을 조금 더 구체화 했습니다.
- 내용을 확인해보시고 좀 더 수정이 필요하거나 잘못 설명한 부분이 있다면 말씀해주시면 수정하겠습니다.
> [chore] 스웨거 설명구체화

- backend/src/main/java/moadong/user/controller/UserController.java
- backend/src/main/java/moadong/user/service/UserCommandService.java
#253 
기존에 userId 반환에서, clubId 반환으로 변경
> [fix] auth/find/club 엔드포인트가 의도대로 작동하지 않는 문제 해결 

- backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
- backend/src/main/java/moadong/user/service/UserCommandService.java
#257 
비밀번호 변경 시 암호화되지 않고 저장되던 문제 수정
> [fix] 비밀번호 변경 시 암호화되지 않고 저장되던 문제 수정

- frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
- frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
> ex) #261 
- 소개글 마크다운 통일했습니다
>
> [fix] 소개글 마크다운 통일

- frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.styles.ts
- frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
- frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
- frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
> #277
- 로그인 화면의 `회원가입 / 아이디 찾기 / 비밀번호 찾기` 항목 클릭 시 안내 메시지(alert) 추가  
→ 현재 미구현된 기능임을 알리고, 관리자에게 문의하도록 유도
- 사이드바에서 로그아웃 클릭 시 `window.confirm()`으로 사용자 확인 절차 추가  
→ 실수로 로그아웃되는 경험 방지
- 사진 업로드 성공시 alert은 제거
또 추가하면 좋은 부분이 있을까요?
피드백 대환영
> [feature] 임시 alert UI/UX 개선 (미구현 기능 알림 처리)

- backend/src/main/java/moadong/gcs/controller/ClubImageController.java
- backend/src/main/java/moadong/gcs/service/ClubImageService.java
> [fix] 이미지 업로드 버그 수정

- frontend/src/App.tsx
- frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
- frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
> ex) #290 
- clubName으로 url변경하니 공유했을때 접속이 안 됨
- 다시 복구했읍니다..
>
> [fix] 상세페이지 url 접속 안 됨 해결

- frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
> [fix] sidebar conflict 해결

- frontend/public/index.html
> [feature] 네이버 서치어드바이저 메타태그 추가

- frontend/src/index.tsx
> ex) #308 
- 콘솔에 projectId 노출되는 문제 발생 
- -> debug 설정 false로 변경 
>
> fix: debug false로 설정

- .github/workflows/create-jira-issue.yml
> [fix] jira 연결 브랜치 develop-fe로 변경

- frontend/package-lock.json
- frontend/package.json
- frontend/src/index.tsx
> ex) #322 
| 클릭 시 처음 보이는 화면 | 채팅방 화면 |
|---------|---------|
| <img width="380" alt="스크린샷 1" src="https://github.com/user-attachments/assets/7715299b-e444-483c-9c16-62ed7a3e552d" /> | <img width="358" alt="스크린샷 2" src="https://github.com/user-attachments/assets/67dbb3fa-12d9-497c-88c6-e891b151aea0" /> |
- 관리자 측에서 피드백 받을 때는 60명 내외로 수가 적어 구글폼으로 진행해왔습니다.
- 다만, 피드백을 받기 위해서는 사용자가 불편함을 느꼈을 즉시 받는게 효과적이라고 생각했습니다.
- 추가로 구글폼 방식은 실시간으로 사용자와 소통할 수 없고, 피드백을 관리하는게 어렵다고 판단했습니다. (구글폼 링크 게시, 피드백 반영 여부 관리)
- 따라서 ```즉시 피드백```에 효과적인 채널톡을 사용하는 것이 추후 일반 사용자들에게 배포할 때 유용할 것이라 생각했습니다.
>
> [feature] 채널톡 추가

- frontend/src/index.tsx
> ex) #322
- 이전pr 수정작업 까먹고 푸쉬을 안 해서 다시 올립니다
>
> [refactor] 채널톡 key이름 변경 및 조건문으로 타입검사

- .github/workflows/codecov.yml
> [chore] codecov 수동 실행 추가

- .github/workflows/codecov.yml
> ex) #이슈번호, #이슈번호
- fetch-depth 옵션을 올바른 위치로 이동:
- actions/checkout 스텝으로 이동.
- codecov 스텝에서는 제거.
>
> [fix] fetch-depth 위치 이동

- .github/workflows/oracle_server_cd_develop.yml
> #517 
> gcloud와 docker가 연동안되는 오류가있었음
> 수동으로 access token으로 인증
>
> [fix] oracle ci/cd 권한인증 오류 수정
